global: &global
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  encoding: utf8

development:
  database: fortune_teller_development
  <<: *global

test: &test
  database: fortune_teller_test<%=ENV['TEST_ENV_NUMBER']%>
  <<: *global

production:
  database: fortune_teller_production
  <<: *global
